# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish Console App

permissions:
  contents: write

on:
  push:
    tags:
    - "*"
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
         
    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build console app
      run: dotnet build -c Release

    - name: Publish console app
      run: dotnet publish -c Release -r linux-x64 --sc -p:PublishSingleFile=true --output ./publish

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: publish/pll
        token: ${{ secrets.GITHUB_TOKEN }}
